"""
Django settings for UserService project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from UserService.settings.sub_settings import *

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent
env = environ.Env()
READ_DOT_ENV_FILE = env.bool("DJANGO_READ_DOT_ENV_FILE", default=True)
if READ_DOT_ENV_FILE:
    # OS environment variables take precedence over variables from .env
    # env.read_env(str(BASE_DIR / ".envs" / f".env.{env.str('ENVIRONMENT_SETTING', 'local')}"))
    env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@5f+3%%4az@#+wpk8&dt9^4gkryd6)m4)gpxsm#4f+ypy)#us6'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env.bool('DEBUG', default=False)
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['*'])

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'statics'),
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'easy_thumbnails',
    'mptt',
    'adrf',
    'rest_framework',
    'drf_yasg',
    'django_healthchecks',
    'apps.address',
    'apps.cameras',
    'apps.users',
    'apps.places',
    'apps.commons',
    'apps.audio_device',
    'apps.services',
    'apps.enterprise',
    'apps.uac',
    'apps.iot',
    'apps.api',
    'apps.iMei',
    'apps.mobile_auth',
    'apps.notifications',
    'apps',
    'corsheaders',
]

AUTH_USER_MODEL = 'applications.users.Customer'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'apps.api.middleware.LanguageMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UserService.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(
                BASE_DIR, 'venv/Lib/site-packages/drf_yasg/templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UserService.wsgi.application'

DJANGO_PROJECT_NAME = 'UserService'
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env.str('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': env.str('DB_DEFAULT_NAME', default=os.path.join(BASE_DIR, 'db.sqlite3')),
        'USER': env.str('DB_DEFAULT_USER', default=''),
        'PASSWORD': env.str('DB_DEFAULT_PASSWORD', default=''),
        'HOST': env.str('DB_DEFAULT_HOST', default=''),
        'PORT': env.str('DB_DEFAULT_PORT', default=''),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4_0900_as_ci',
        },
        'CONN_MAX_AGE': 60,
    },
    'db_read': {
        'ENGINE': env.str('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': env.str('DB_DEFAULT_NAME', default=os.path.join(BASE_DIR, 'db.sqlite3')),
        'USER': env.str('DB_DEFAULT_USER', default=''),
        'PASSWORD': env.str('DB_DEFAULT_PASSWORD', default=''),
        'HOST': env.str('DB_DEFAULT_HOST', default=''),
        'PORT': env.str('DB_DEFAULT_PORT', default=''),
        'CONN_MAX_AGE': env.int("DB_DEFAULT_CONN_MAX_AGE", default=60),
        'TEST': {
            'CHARSET': 'utf8mb4',
            'COLLATION': 'utf8mb4',
        },
    }
}

DATABASE_ROUTERS = ['UserService.db_router.DbRouter', ]

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_TZ = True

USE_I18N = True

USE_L10N = True

LANGUAGES = [
    ('en', 'English'),
    ('vi', 'Vietnamese'),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

CODE_STATUS_API = {
    '200': 1200,
    '201': 1201,
    '202': 1202,
    '400': 1400,
    '401': 1401,
    '402': 1402,
    '403': 1403,
    '404': 1404,
    '405': 1405,
    '406': 1406,
    '407': 1407,  # Mã thộng báo mất quyền truy cập
    '418': 1418,  # Payment invoice invalid
    '440': 1440,  # Mã thông báo license hết hạn.
    # Mã Thông báo license được gia hạn yêu cầu app renew license mới.
    '444': 1444,
    '445': 1445,  # Mã Thông báo mất quyền truy cập công ty
    '446': 1446,  # Mã Thông báo khi không tìm thấy input user ở api_user_access_control
    "447": 1447,  # Mã Thông báo kht mất quyền truy cập camera hoặc place
    "448": 1448,  # Mã Thông báo để app hiển thị snackbar
    "449": 1449,  # Mã Thông báo để app hiển thị backdrop
    "450": 1450,  # Mã Thông báo de app hien thi loi o nhap trong
    '500': 1500,
    '700': 1700,  # Mã Thng báo duplicate hình ảnh nhận diện
    '200_for_isc': 200,  # Phia anh manh yeu cau chinh cho MBS, API api_gift_codes_notification
}

HTTP_STATUS_CODES = {
    "informational": {
        "CODE_STATUS_CONTINUE": 100,
        "CODE_STATUS_SWITCHING_PROTOCOLS": 101,
        "CODE_STATUS_PROCESSING": 102,
    },
    "success": {
        "CODE_STATUS_SUCCESS": 200,
        "CODE_STATUS_CREATED": 201,
        "CODE_STATUS_ACCEPTED": 202,
        "CODE_STATUS_NON_AUTHORITATIVE_INFORMATION": 203,
        "CODE_STATUS_NO_CONTENT": 204,
        "CODE_STATUS_RESET_CONTENT": 205,
        "CODE_STATUS_PARTIAL_CONTENT": 206,
    },
    "redirection": {
        "CODE_STATUS_MULTIPLE_CHOICES": 300,
        "CODE_STATUS_MOVED_PERMANENTLY": 301,
        "CODE_STATUS_FOUND": 302,
        "CODE_STATUS_SEE_OTHER": 303,
        "CODE_STATUS_NOT_MODIFIED": 304,
        "CODE_STATUS_TEMPORARY_REDIRECT": 307,
        "CODE_STATUS_PERMANENT_REDIRECT": 308,
    },
    "client_error": {
        "CODE_STATUS_BAD_REQUEST": 400,
        "CODE_STATUS_UNAUTHORIZED": 401,
        "CODE_STATUS_FORBIDDEN": 403,
        "CODE_STATUS_NOT_FOUND": 404,
        "CODE_STATUS_METHOD_NOT_ALLOWED": 405,
        "CODE_STATUS_NOT_ACCEPTABLE": 406,
        "CODE_STATUS_REQUEST_TIMEOUT": 408,
        "CODE_STATUS_CONFLICT": 409,
        "CODE_STATUS_GONE": 410,
        "CODE_STATUS_PAYLOAD_TOO_LARGE": 413,
        "CODE_STATUS_URI_TOO_LONG": 414,
        "CODE_STATUS_UNSUPPORTED_MEDIA_TYPE": 415,
        "CODE_STATUS_TOO_MANY_REQUESTS": 429,
    },
    "server_error": {
        "CODE_STATUS_INTERNAL_SERVER_ERROR": 500,
        "CODE_STATUS_NOT_IMPLEMENTED": 501,
        "CODE_STATUS_BAD_GATEWAY": 502,
        "CODE_STATUS_SERVICE_UNAVAILABLE": 503,
        "CODE_STATUS_GATEWAY_TIMEOUT": 504,
        "CODE_STATUS_HTTP_VERSION_NOT_SUPPORTED": 505,
        "CODE_STATUS_INSUFFICIENT_STORAGE": 507,
    }
}

KEY_LIST = {
    'android': 'fd37f466ad4144ae89246ec5f3365bc9',
    'ios': '00e1dbad838b41679464d38fa572c18e',
    'web': 'c5e7a47f2d334dddbcc1ba50adf370f0',
    'box': 'cklmmasmfn28564dddbcc1ba50adf370ng2',
    'desktop': 'cklmmasmfn28564dddbcc1ba50adf370ng2',
    'fsh': 'cklmmasmfn28564dddbcc1ba50adf370ng2',
    'enterprise-ios': 'vlfu1zruz3iyvgnq2jyp3izkjoovluuf',
    'enterprise-android': 'm6g2zgnxqgldhf2h8sgwwgqu2dmsy5a5',
    'enterprise-desktop': 'r7jfq9tvgjkaej7bi106u9uwinuvzeeg',
    'enterprise-web': '078b2691a7fc41169d886da8f876c8b3',
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
MAX_SIZE_FILE = 10 * 1024 * 1024
BACKUP_COUNT = 30
os.makedirs(LOGS_DIR, exist_ok=True)

IS_CONSOLE_LOG = bool(os.getenv('IS_CONSOLE_LOG', True))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
        'detailed': {
            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] [%(funcName)s] %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
    },
    'handlers': {
        "console_info": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "stream": "ext://sys.stdout",
        },
        "console_error": {
            "level": "ERROR",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "stream": "ext://sys.stderr",
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'api.log'),
            'maxBytes': MAX_SIZE_FILE,
            'backupCount': BACKUP_COUNT,
            'formatter': 'verbose',
            'level': 'DEBUG',
            'encoding': 'utf-8',
        },
        'keycloak_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'keycloak_handler.log'),
            'maxBytes': MAX_SIZE_FILE,
            'backupCount': BACKUP_COUNT,
            'formatter': 'detailed',
            'level': 'DEBUG',
            'encoding': 'utf-8',
        },
        'consumer_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'kafka_consumer.log'),
            'maxBytes': MAX_SIZE_FILE,
            'backupCount': BACKUP_COUNT,
            'formatter': 'detailed',
            'level': 'DEBUG',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        '': {  # Root logger
            'handlers': ['console_info' if IS_CONSOLE_LOG else 'console_info', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console_info' if IS_CONSOLE_LOG else 'console_info', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['console_info' if IS_CONSOLE_LOG else 'console_info', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console_info' if IS_CONSOLE_LOG else 'console_info', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.uac.utils': {
            'handlers': ['console_info' if IS_CONSOLE_LOG else 'console_info', 'keycloak_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.commons.management.commands.consumers': {
            'handlers': ['console_info' if IS_CONSOLE_LOG else 'console_info', 'consumer_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'kafka': {
            'handlers': ['console_info' if IS_CONSOLE_LOG else 'console_info', 'consumer_file'],
            'level': 'INFO',
            'propagate': False,
        },
    }
}

MASTER_ROLE = {
    "Admin": {
        "id": "c00f400e-95fb-427b-9ddd-ebaeccf39ebb",
        "name": "Admin",
        "description": "",
        "composite": False,
        "clientRole": False,
        "containerId": "9f679ac9-f1f1-47be-999c-0dbadb77ee18",
        "policy_id": "f1b60790-6332-4a13-9aa6-a06b926d797f",
        "attributes": {
            "organization": [
                "FLI"
            ]
        }
    },
    "Basic Sharer": {
        "id": "1fdfcd1d-6a9c-4ce8-9f66-04aee1124ab9",
        "name": "Basic Sharer",
        "description": "",
        "composite": False,
        "clientRole": False,
        "containerId": "9f679ac9-f1f1-47be-999c-0dbadb77ee18",
        "policy_id": "ce18dfa1-484a-4c9f-86ee-eb31d1ba0a4b",
        "attributes": {
            "organization": [
                "FLI"
            ]
        }
    },
    "Owner": {
        "id": "61e05345-ee58-424b-b779-0cadc7f9c8bb",
        "name": "Owner",
        "composite": False,
        "clientRole": False,
        "containerId": "9f679ac9-f1f1-47be-999c-0dbadb77ee18",
        "policy_id": "77a9a84b-862d-4da1-8b09-abf8d8108784",
        "attributes": {
            "organization": [
                "FLI"
            ]
        }
    },
    "Technician": {
        "id": "6b2d8c9a-bc8f-41c1-8105-938478a3ca46",
        "name": "Technician",
        "description": "",
        "composite": False,
        "clientRole": False,
        "containerId": "9f679ac9-f1f1-47be-999c-0dbadb77ee18",
        "policy_id": "f9158f72-ae5c-43a0-848d-5aab50831d0f",
        "attributes": {
            "organization": [
                "FLI"
            ]
        }
    },
    "SysAdmin": {
        "id": "192bef84-aca6-4dbd-b70f-16ac7e171f97",
        "name": "SysAdmin",
        "description": "",
        "composite": False,
        "clientRole": False,
        "containerId": "9f679ac9-f1f1-47be-999c-0dbadb77ee18",
        "policy_id": "a4cfacb8-4358-42b0-87a7-e3041f700239",
        "attributes": {
            "organization": [
                "FLI"
            ]
        }
    }
}

AFFIRMATIVE = env.str('AFFIRMATIVE', default='AFFIRMATIVE')
UNANIMOUS = env.str('AFFIRMATIVE', default='UNANIMOUS')
CONSENSUS = env.str('AFFIRMATIVE', default='CONSENSUS')
PHONENUMBER_DEFAULT_CODE = env.list('PHONENUMBER_DEFAULT_CODE', default=['84', '1'])
JWT_SIGN = env.str('JWT_SIGN', default='9y$B?E(H+MbQeThWmZq4t7w!z%C*F)J@')
JWT_ENCRYPT_KEY = env.str('JWT_SIGN', default='J@NcQfTjWnZr4u7x!A%D*G-KaPdSgUkX')
NAME_ENTITY = {
    "trach-nhiem-huu-han": "TNHH",
    "va": "&",
    "cong-ty": "Cty",
    "hop-danh": "HD",
    "co-phan": "CP",
    "thuong-mai": "TM",
    "giao-duc": "GD",
    "san-xuat": "SX",
    "mot-thanh-vien": "MTV",
    "tieu-hoc": "TH",
    "xay-dung": "XD",
    "trung-hoc-co-so": "THCS",
    "dich-vu": "DV"
}
ALL_DEVICES_ID = env.str('ALL_DEVICES_ID', default='31135595-7533-41ad-b075-4e9a47d3ddb4')
ALL_DEVICES_NAME = env.str('ALL_DEVICES_NAME', default='All')
ROLE_FEATURES_CACHE_PATTERN = "role_{}"
UAC_RESOURCES = "uac_{}_resources"
CACHE_TIME = int(env('CACHE_TIME', default=2*60))
CACHE_DB_TIME = int(env('CACHE_DB_TIME', default=1*60))
REFRESH_TOKEN_CACHE_TIME = int(env('REFRESH_TOKEN_CACHE_TIME', default=60*60*24*30))
CACHE_RESOURCE_KEY = env.str('CACHE_RESOURCE_KEY', default='resource_data')
CLIENT_ID = env.str('CLIENT_ID', default='resource-admin')
SERVICE_NAME = env.str('SERVICE_NAME', default='betaBusinessResourceMngtB2B')
JAEGER_DOMAIN = env.str('JAEGER_DOMAIN', default='jaeger-beta.fcam.vn')

AUTHORIZE_SERVICE_URL = env.str('AUTHORIZE_SERVICE_URL', default='https://beta-api-gateway.fcam.vn/authorization/permissions')
PASS_ENC = env.str('PASS_ENC', default='3i4852bf(#384jbr')

# fss-mngt
FSS_MANAGEMENT_PROTOCOL = env.str('FSS_MANAGEMENT_PROTOCOL', default='https')
FSS_MANAGEMENT_HOST = env.str('FSS_MANAGEMENT_HOST', default='beta-fss-mngt.fcam.vn')
FSS_MANAGEMENT_GIS = env.str('FSS_MANAGEMENT_GIS', default='a8a55ef4e4924c2dbf2f80be8cff14de')

# sms server
SENDSMS_BACKEND = env.str('SENDSMS_BACKEND', default='sendsms.backends.console.SmsBackend')
SMS_API_URL = env.str('SMS_API_URL', default='http://sms.fpt.vn/Service1.asmx/SendSMS')
STAFF_ID_SMS = env.str('STAFF_ID_SMS', default='0')
LOCATION_ID_SMS = env.str('LOCATION_ID_SMS', default='8')
RESOURCE_ID_SMS = env.str('RESOURCE_ID_SMS', default='5c1261a119f2b87a396d3da9989327a6')
EMAIL_RECEIVE_LIST = env.list('EMAIL_RECEIVE_LIST', default=['duytp3@fpt.com.vn',
                      'thiennhm@fpt.com.vn', 'duylt18@fpt.com.vn', 'huynd78@fpt.com.vn'])

# Mobile Auth
PHONENUMBER_DEFAULT_REGION = env.str('PHONENUMBER_DEFAULT_REGION', default='VN')
PHONENUMBER_DEFAULT_LENGTH = env.int('PHONENUMBER_DEFAULT_LENGTH', default=9)
PHONE_LOGIN_MINUTES = env.int('PHONE_LOGIN_MINUTES', default=2)
PHONE_LOGIN_ATTEMPTS = env.int('PHONE_LOGIN_ATTEMPTS', default=3)
PHONE_LOGIN_OTP_LENGTH = env.int('PHONE_LOGIN_OTP_LENGTH', default=4)
EMAIL_OTP_LENGTH = env.int('EMAIL_OTP_LENGTH', default=4)
EMAIL_OTP_EXPIRATION = env.int('EMAIL_OTP_EXPIRATION', default=2)
EMAIL_OTP_ATTEMPTS = env.int('EMAIL_OTP_ATTEMPTS', default=3)

IS_VALIDATE_OTP_REQUIRED = env.bool('IS_VALIDATE_OTP_REQUIRED', default=True)
IS_SSO_VALIDATE_OTP_REQUIRED = env.bool('IS_SSO_VALIDATE_OTP_REQUIRED', default=True)

SMS_API_V2_URL = env.str('SMS_API_V2_URL', default='http://sms.fpt.vn/Service1.asmx/SendSMS')
EMAIL_API_V2_URL = env.str('EMAIL_API_V2_URL', default='https://beta-api-gateway.fcam.vn/notification/api/notifications/')
EMAIL_API_GIS = env.str('EMAIL_API_GIS', default='8f2e3c8a5f1d4f2eaed8f5b1f5e4f2b6')


SMS_TO_SEND_OTP = 'FPT Telecom thong bao {} la ma xac thuc ung dung FPT VMSmart cua Quy khach. Xin cam on!'
SMS_TO_SEND_EXPIRED = '[FPT VMSmart] Quy khach co {} camera se het han luu tru cloud vao ngay {}, vui long gia han goi cuoc tren ung dung FPT VMSmart. Xin cam on!'

DEVICE_NAME_DICT = {
    "iPod5,1": "iPod touch (5th generation)",
    "iPod7,1": "iPod touch (6th generation)",
    "iPod9,1": "iPod touch (7th generation)",
    "iPhone3,1": "iPhone 4",
    "iPhone3,2": "iPhone 4",
    "iPhone3,3": "iPhone 4",
    "iPhone4,1": "iPhone 4s",
    "iPhone5,1": "iPhone 5",
    "iPhone5,2": "iPhone 5",
    "iPhone5,3": "iPhone 5c",
    "iPhone5,4": "iPhone 5c",
    "iPhone6,1": "iPhone 5s",
    "iPhone6,2": "iPhone 5s",
    "iPhone7,2": "iPhone 6",
    "iPhone7,1": "iPhone 6 Plus",
    "iPhone8,1": "iPhone 6s",
    "iPhone8,2": "iPhone 6s Plus",
    "iPhone8,4": "iPhone SE",
    "iPhone9,1": "iPhone 7",
    "iPhone9,3": "iPhone 7",
    "iPhone9,2": "iPhone 7 Plus",
    "iPhone9,4": "iPhone 7 Plus",
    "iPhone10,1": "iPhone 8",
    "iPhone10,4": "iPhone 8",
    "iPhone10,2": "iPhone 8 Plus",
    "iPhone10,5": "iPhone 8 Plus",
    "iPhone10,3": "iPhone X",
    "iPhone10,6": "iPhone X",
    "iPhone11,2": "iPhone XS",
    "iPhone11,4": "iPhone XS Max",
    "iPhone11,6": "iPhone XS Max",
    "iPhone11,8": "iPhone XR",
    "iPhone12,1": "iPhone 11",
    "iPhone12,3": "iPhone 11 Pro",
    "iPhone12,5": "iPhone 11 Pro Max",
    "iPhone12,8": "iPhone SE (2nd generation)",
    "iPad2,1": "iPad 2",
    "iPad2,2": "iPad 2",
    "iPad2,3": "iPad 2",
    "iPad2,4": "iPad 2",
    "iPad3,1": "iPad (3rd generation)",
    "iPad3,2": "iPad(3rd generation)",
    "iPad3,3": "iPad (3rd generation)",
    "iPad7,5": "iPad (6th generation)",
    "iPad7,6": "iPad (6th generation)",
    "iPad7,11": "iPad (7th generation)",
    "iPad7,12": "iPad (7th generation)",
    "iPad4,1": "iPad Air",
    "iPad4,2": "iPad Air",
    "iPad4,3": "iPad Air",
    "iPad5,3": "iPad Air 2",
    "iPad5,4": "iPad Air 2",
    "iPad11,4": "iPad Air (3rd generation)",
    "iPad11,5": "iPad Air (3rd generation)",
    "iPad2,5": "iPad mini",
    "iPad2,6": "iPad mini",
    "iPad2,7": "iPad mini",
    "iPad4,4": "iPad mini 2",
    "iPad4,5": "iPad mini 2",
    "iPad4,6": "iPad mini 2",
    "iPad4,7": "iPad mini 3",
    "iPad4,8": "iPad mini",
    "iPad11,1": "iPad mini (5th generation)",
    "iPad11,2": "iPad mini (5th generation)",
    "iPad6,3": "iPad Pro (9.7-inch)",
    "iPad6,4": "iPad Pro (9.7-inch)",
    "iPad7,3": "iPad Pro (10.5-inch)",
    "iPad7,4": "iPad Pro (10.5-inch)",
    "iPad8,1": "iPad Pro (11-inch) (1st generation)",
    "iPad8,2": "iPad Pro (11-inch) (1st generation)",
    "iPad8,3": "iPad Pro (12.9-inch) (2nd generation)",
    "iPad8,5": "iPad Pro (12.9-inch) (3rd generation)",
    "iPad8,6": "iPad Pro (12.9-inch) (3rd generation)",
    "iPad8,7": "iPad Pro (12.9-inch) (3rd generation)",
    "iPad8,8": "iPad Pro (12.9-inch) (3rd generation)",
    "iPad8,11": "iPad Pro (12.9-inch) (4th generation)",
    "iPad8,12": "iPad Pro (12.9-inch) (4th generation)",
    "AudioAccessory1,1": "HomePod",
    "AppleTV5,3": "Apple TV 4",
    "AppleTV6,2": "Apple TV 4K",
    "iPhone13,1": "iPhone 12 Mini",
    "iPhone13,2": "iPhone 12",
    "iPhone13,3": "iPhone 12 Pro",
    "iPhone13,4": "iPhone 12 Pro Max",
}

RESOURCE_PATH = os.path.join(BASE_DIR, 'resources', 'device_name.json')

API_ALERT_HOST = env.str('API_ALERT_HOST', default='beta-api-gateway.fcam.vn/notification-b2b')
API_ALERT_GIS = env.str('API_ALERT_GIS', default='c5e7a47f2d334dddbcc1ba50adf370f0')
API_ALERT_PROTOCOL = env.str('API_ALERT_PROTOCOL', default='https')

KAFKA_BOOTSTRAP_SERVERS = env.str('KAFKA_BOOTSTRAP_SERVERS', default='42.119.146.47:29092,42.119.146.48:29092,42.119.146.49:29092')
KAFKA_GROUP_ID = env.str('KAFKA_GROUP_ID', default='brm-consum')
KAFKA_USERNAME = env.str('KAFKA_USERNAME', default='admin-fss')
KAFKA_PASSWORD = env.str('KAFKA_PASSWORD', default='admin-fss')
LICENSE_KEY = env.str('LICENSE_KEY', default='8d79714fb95640b79c4ab4ebb63ddbd2')

API_WEBSOCKET_HOST = env.str('API_WEBSOCKET_HOST', default='prod-wsk.fcam.vn')
API_WEBSOCKET_GIS = env.str('API_WEBSOCKET_GIS', default='21dc2b7fb0244f1a818f40b6ca56d1ad')
API_WEBSOCKET_PROTOCOL = env.str('API_WEBSOCKET_PROTOCOL', default='https')
OTP_TOKEN_EXPIRATION = int(env('OTP_TOKEN_EXPIRATION', default=5))
TOTAL_DEVICE_LIMIT = env.int('TOTAL_DEVICE_LIMIT', default=5)
PHONE_NUMBER_OTP_SPECIAL_LIST = env.list('PHONE_NUMBER_OTP_SPECIAL_LIST', default=['+84900001309', '+84349360321', '+84366791810'])
PHONE_NUMBER_OTP_NOT_LIMIT_LIST = env.list('PHONE_NUMBER_OTP_NOT_LIMIT_LIST', default=['+84900001309', '+84349360321', '+84366791810'])
CUS_URL = env.str('CUS_URL', default='https://beta-api-gateway.fcam.vn/cusmngt-service/inside/uac')
GIS_INSIDE = env.str('GIS_INSIDE', default='fd0b0566ee6845879a1b5223ce8ac6c2')
IAM_TOKEN_VALIDATION_URL = env.str('IAM_TOKEN_VALIDATION_URL', default='https://beta-api-gateway.fcam.vn/customer-b2b/iam/authenticate/user')
IAM_VALIDATION_GIS = env.str('IAM_VALIDATION_GIS', default='d613b860972242138ff17fc451f4e62d')

# Keycloak
BASE_KEYCLOAK_URL = env.str('BASE_KEYCLOAK_URL', default='https://staging-sso.fcam.vn/realms/b2b/protocol/openid-connect')
KEYCLOAK_CLIENT_ID = env.str('KEYCLOAK_CLIENT_ID', default='resource-admin')
KEYCLOAK_CLIENT_SECRET = env.str('KEYCLOAK_CLIENT_SECRET', default='vF7cNGCTnw5RpTiIEvl8OSVZg5NbLr9m')
KEYCLOAK_REFRESH_TOKEN_KEY = env.str('KEYCLOAK_REFRESH_TOKEN_KEY', default='resource_admin_refresh_token')
KEYCLOAK_ADMIN_URL = env.str('KEYCLOAK_ADMIN_URL', default='https://staging-sso.fcam.vn/admin/realms/b2b')
KEYCLOAK_USERNAME = env.str('KEYCLOAK_USERNAME', default='resource_admin')
KEYCLOAK_PASSWORD = env.str('KEYCLOAK_PASSWORD', default='123456')
KEYCLOAK_ADMIN_TOPIC = env.str('KEYCLOAK_ADMIN_TOPIC', default='keycloak_admin_event')
KEYCLOAK_USER_TOPIC = env.str('KEYCLOAK_USER_TOPIC', default='keycloak_user_event')
KEYCLOAK_REALM = env.str('KEYCLOAK_REALM', default='b2b')
KEY_CLOAK_ADMIN_ID = env.str('KEY_CLOAK_ADMIN_ID', default='46d397b4-c297-410b-bfff-a6a12d5c70a0')
KEYCLOAK_DEV_CLIENT_ID = env.str('KEYCLOAK_DEV_CLIENT_ID', default='fli-b2b-brm')
KEYCLOAK_DEV_AUDIENCE = env.str('KEYCLOAK_DEV_AUDIENCE', default='fli-b2b-brm')
KEYCLOAK_URL = "{}/token".format(BASE_KEYCLOAK_URL)
KEYCLOAK_PUBLIC_KEY_URL = "{}/certs".format(BASE_KEYCLOAK_URL)
KEY_CLOAK_IAM_ADMIN_URL = env.str('KEY_CLOAK_IAM_ADMIN_URL', default='https://beta-api-gateway.fcam.vn/iam-mgt/private/iam')
AUDIENCE_ACCESS_TOKEN = env.str('AUDIENCE_ACCESS_TOKEN', default='account')
AUDIENCE_RESOURCE = env.str('AUDIENCE_RESOURCE', default='resource-admin')
KEYCLOAK_ACCESS_TOKEN_KEY = env.str('KEYCLOAK_ACCESS_TOKEN_KEY', default='keycloak')
KEYCLOAK_SECRET = env.str('KEYCLOAK_SECRET', default='KSG8aqWPWIpFBE9HG1Ojf6YcewgwDId7')
PUBLIC_KEY_CACHE_TIME = int(env('PUBLIC_KEY_CACHE_TIME', default=5 * 60))

# Opensearch
OPENSEARCH_SERVICE_PROTOCOL = os.getenv('OPENSEARCH_SERVICE_PROTOCOL', default='http')
OPENSEARCH_SERVICE_URL = os.getenv('OPENSEARCH_SERVICE_URL', default='beta-es-moment.fcam.vn')
OPENSEARCH_SERVICE_HOST = os.getenv('OPENSEARCH_SERVICE_HOST', default='beta-es-moment.fcam.vn')
OPENSEARCH_SERVICE_PORT = int(os.getenv('OPENSEARCH_SERVICE_PORT', default=80))
OPEN_SEARCH_USERNAME = os.getenv('OPEN_SEARCH_USERNAME', default='backend')
OPEN_SEARCH_PASSWORD = os.getenv('OPEN_SEARCH_PASSWORD', default='Backend@123')
KAFKA_OPEN_SEARCH_GROUP_ID = env.str('KAFKA_OPEN_SEARCH_GROUP_ID', default='user-log')
KAFKA_RESULT_USER_LOG_TOPIC = os.getenv('KAFKA_RESULT_USER_LOG_TOPIC', default='user_log_event')
USER_LOG_RESULT_META_INDEX_FORMAT = os.getenv('USER_LOG_RESULT_META_INDEX_FORMAT', default='user-log-result-meta-{}')
GIS_VALIDATION_KEY = os.getenv('BRM_API_GIS', default='e0241d2e185f4cd5a1d53d21c0ef7d81')
LIST_OBJECT_TYPE = os.getenv('LIST_OBJECT_TYPE', default=['nvr', 'camera', 'user', 'company', 'role', 'place', 'groupplace'])
LIST_ACTION_TYPE = os.getenv('LIST_ACTION_TYPE', default=['add', 'delete', 'update', 'access', 'livestream', 'playback', 'assign'])
KAFKA_USER_LOG_EVENT_GROUP_ID = env.str('KAFKA_USER_LOG_EVENT_GROUP_ID', default='user-log-group')
USER_LOG_USERNAME_INDEX_FORMAT = "user_log_usernames"
FILER_LIST_KEY = "filter_list_key"
DEFAULT_PLACE_MODEL = {
    'vi': {
        'name': 'FCC98BE14F9A4FFAA83A67FA934B5E16',
        'address': '',
        'city': '',
        'is_default': True
    },
    'en': {
        'name': 'FCC98BE14F9A4FFAA83A67FA934B5E16',
        'address': '',
        'city': '',
        'is_default': True
    },
}
UAC_FLAT_RESOURCES = "uac_flat_{}_{}_resources"

API_MANAGEMENT_GIS = os.getenv('API_MANAGEMENT_GIS', default='d0241d2e185f4cd5a1d53d21c0ef8df2')
API_MANAGEMENT_HOST = os.getenv('API_MANAGEMENT_HOST', default='beta-api-gateway.fcam.vn/cmrmngt-b2b')
API_MANAGEMENT_PROTOCOL = os.getenv('API_MANAGEMENT_PROTOCOL', default='https')
DEFAULT_PASSWORD = os.getenv('DEFAULT_PASSWORD', default='Admin123456')
COUNTDOWN_TIME_SYNC_SSO = os.getenv('COUNTDOWN_TIME_SYNC_SSO', default=120)
ALLOWED_GIS = os.getenv('ALLOWED_GIS', default='1e1a6949d1474b50b51d97abb92a69a3')
